# Generated by Django 3.1.5 on 2021-01-30 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sekolah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npsn', models.CharField(max_length=30)),
                ('name_school', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('logo_school', models.CharField(max_length=2000)),
                ('school_level', models.CharField(max_length=60)),
                ('status_school', models.CharField(max_length=60)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
